services:
  config.extension:
      class: ConfigurationBundle\Extension\ConfigExtension
      public: true
      tags:
        - { name: twig.extension }
      arguments:
        - "@doctrine.orm.default_entity_manager"
