<?php

namespace ConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{

    /**
     * Cache for runtime values
     * @var array
     */
    protected $cacheValues = [];

    /**
     * Get config var if exists
     * @param $name
     * @param string $fallback
     * @return string
     */
    public function getConfigVar($name, $fallback=null)
    {
        if(array_key_exists($name,$this->cacheValues)){
            return $this->cacheValues[$name];
        }
        /** @var Configuration $config */
        $config = $this->findOneBy([
            'name' => trim($name)
        ]) ;
        switch(true){
            case $config instanceof Configuration && $config->getType() == 'dropdown' && $config->getValue() == 'false':
                $this->cacheValues[$name] = false;
                return false;
            case $config instanceof Configuration && $config->getType() == 'dropdown' && $config->getValue() == 'true':
                $this->cacheValues[$name] = true;
                return true;
            case (empty($config) || !$config->getValue()) && $fallback !== null:
                $this->cacheValues[$name] = $fallback;
                break;
            case empty($config):
            case !$config->getValue():
                $this->cacheValues[$name] = 'configuration '.$name.' not found';
                break;
            default:
                $this->cacheValues[$name] = $config->getValue();
        }
        return $this->cacheValues[$name];


    }

    /**
     * Arrays können in der Textarea auch in dieser Form gespeichert werden:
     * Name1 => Wert1
     * Name2 => Wert2
     * @param $name
     * @return array
     */
    public function getConfigVarAsArray($name)
    {
        if(array_key_exists($name,$this->cacheValues)){
            return $this->cacheValues[$name];
        }
        $value = $this->getConfigVar($name);
        if(strpos($value, 'not found') !== false){
            return [];
        }
        $returnValues = [];
        $values = explode("\n", $value);
        foreach ($values as $index => $value){
            if(strpos($value, '=>') !== false){
                $tmpValue = explode('=>', $value);
                $returnValues[trim($tmpValue[0])] = trim($tmpValue[1]);
            }else{
                $returnValues[$index] = trim($value);
            }
        }
        $this->cacheValues[$name] = $returnValues;
        return $returnValues;
    }

    /**
     *
     * @param $name
     * @param $value
     * @param string $group
     */
    public function addVarToConfigArray($name, $value, $group = 'Systemeinstellungen'){
        /** @var Configuration $config */
        $config = $this->findOneBy([
            'name' => trim($name)
        ]) ;
        if(empty($config)){
            $config = new Configuration();
            $config->setValue(trim($value))
                ->setName($name)
                ->setGroup($group)
                ->setType('dropdown');
        }else{
            $newValue = $config->getValue();
            $newValue .= "\n".trim($value);
            $arValue = explode("\n", $newValue);
            $arValue = array_unique($arValue);
            $config->setValue(implode("\n", $arValue));
        }
        $this->_em->persist($config);
        $this->_em->flush();
        $this->cacheValues = [];
    }


    /**
     * Check if config var exists and not empty
     * @param $name
     * @return bool
     */
    public function isConfigVarExists($name)
    {
        $config = $this->findOneBy([
            'name' => trim($name)
        ]) ;

        if(empty($config)){
            return false;
        }
        if(!$config->getValue()){
            return false;
        }
        return true;
    }

    /**
     * @param bool $withPrivate
     * @return array
     */
    public function getOnlyGroups($withPrivate = false){
        $query = $this->createQueryBuilder('c');
        $query->select('c.group');
        if($withPrivate){
            $query->where('c.public < 1' );
        }else{
            $query->where('c.public = 1' );
        }
        $query->addGroupBy('c.group');
        return $query->getQuery()->getResult();
    }
}
